title: "Мой сайт"
description: "Лендинг + блог"
url: "https://mysite.com"   # поменяй на свой домен
baseurl: ""                 # если блог будет на blog.mysite.com — оставь пустым

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
