title: "evPoint.kz"
description: ""
url: "https://blog.evpoint.kz"
baseurl: ""

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

author: John Smith

# 🗺️ Локализация (для поиска)
lang: "ru"
timezone: "Asia/Almaty"

# 🔍 Дополнительно: чтобы GitHub Pages не ругался
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor