title: "Мой сайт"
description: "Лендинг + блог"
url: "https://blog.evpoint.kz"   # поменяй на свой домен
baseurl: ""                 # если блог будет на blog.mysite.com — оставь пустым

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
